name: venv_forensic
channels:
  - defaults
dependencies:
  - python=3.12.0
  - pip:
    - numpy==1.26
    - imageio==2.31.4
    - scipy==1.11.3
    - scikit-image==0.22.0
    - Cython==3.0.5
    - nibabel
    - pynrrd==1.0.0
